const feedsList = [
  "http://www.christianarchy.nl/feeds/posts/default?alt=rss",
  "http://www.konfrontatie.nl/rss.xml",
  "https://1872dh.noblogs.org/feed/",
  "https://a-bieb.nl/feed",
  "https://aagu.nl/rss",
  "https://abcnijmegen.wordpress.com/feed",
  "https://afadenhaag.wordpress.com/feed",
  "https://ak-utrecht.nl/rss.xml",
  "https://anarchief.nl/feed/",
  "https://anarchistischegroepnijmegen.nl/rss.xml",
  "https://anarchistischkollektief.wordpress.com/rss",
  "https://anticrust0.noblogs.org/feed",
  "https://antithese.blackblogs.org/feed",
  "https://autonomenbrabant.blackblogs.org/feed",
  "https://bondprecairewoonvormen.nl/feed",
  "https://buitendeorde.org/rss",
  "https://controlealtdelete.nl/rss/feed.xml",
  "https://indy.puscii.nl/rss.xml",
  "https://kafka.nl/rss",
  "https://www.krapuul.nl/category/mededeling/feed/",
  "https://www.krapuul.nl/category/natuur-en-milieu-2/feed/",
  "https://www.krapuul.nl/category/overig/inzending-tips-overig-2/feed/",
  "https://www.krapuul.nl/category/politiek-blog/feed/",
  "https://libertaireorde.wordpress.com/feed",
  "https://onderstroom.red/feed",
  "https://opstand.noblogs.org/feed",
  "https://peterstormt.nl/author/ravotr/rss",
  "https://socialisme.nu/feed",
  "https://tanarchos.nl/feed",
  "https://thebarricade.noblogs.org/feed",
  "https://vloerwerk.org/feed",
  "https://vrijesocialist.wordpress.com/rss",
  "https://www.2dh5.nl/rss",
  "https://www.agamsterdam.org/rss",
  "https://www.burojansen.nl/rss",
  "https://www.doorbraak.eu/feed",
  "https://www.globalinfo.nl/feed/rss.html",
  "https://www.grenzeloos.org/rss.xml",
  "https://www.grutjes.nl/feed",
  "https://www.hierlinksaf.nl/Podcast/ABC/feed.xml",
  "https://www.hierlinksaf.nl/Podcast/Audioboek/feed.xml",
  "https://www.vrijebond.org/feed",
  "https://rumoer.noblogs.org/feed/",
  "https://lepelfabriek.nl/rss.xml",
  // 'https://lepelfabriek.nl/blog/index.php/feed', // Geen rss
  // 'https://lorem-rss.herokuapp.com/feed?unit=second&interval=30'
]

export default feedsList
